version: "3.7"

services:

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php_server
        volumes:
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./server:/apps/server
        working_dir: /apps/server
        environment:
            TIMEZONE: ${TIMEZONE}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "80:80"
        depends_on:
            - postgres
        networks:
            - devops

    postgres:
        build:
            context: .
            dockerfile: ./docker/pgsql/Dockerfile
        container_name: postgres_db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/react-symfony
        volumes:
            - pgdata:/var/lib/postgresql/data/react-symfony
            - ./backups:/backups
        ports:
            - "5432:5432"
        networks:
            devops:
                aliases:
                    - postgres.docker

volumes:
    pgdata:
        driver: local

networks:
    devops: