doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%env(resolve:POSTGRES_HOST)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        server_version: '12'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)  %env(resolve:POSTGRES_HOST)%
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
